### ISSUE TITLE
zcompare:zcompile:2: can't write zwc file

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#44]
- Zim commit ref: https://github.com/Eriner/zim/commit/4ac66646c496225ce8a8714b6a2fcabff32aa851
- gist of .zimrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zimrc
- Zsh version: `5.2-1`
- gist of .zshrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zshrc
- $(uname -mosr): `Linux 4.4.7-1-ck x86_64 GNU/Linux`

Description
-----------
Opening tmux spams the terminal with a bunch of `zcompare:zcompile:2: can't write zwc file: /usr/lib/zim/modules/git/init.zsh.zwc` messages.

While trying to troubleshoot [a bug](https://bbs.archlinux.org/viewtopic.php?pid=1621064), I had to test ZSH with vanilla. I uninstalled Zim and reset my `.zshrc` file. After I was done, I moved back my `.zshrc` file and then reinstalled Zim. When I reinstalled it, I had to rebuild it, so I got the new commits. I assume a recent commit caused this to happen.

Steps to reproduce
------------------
1. Use commit https://github.com/Eriner/zim/commit/4ac66646c496225ce8a8714b6a2fcabff32aa851
2. Open a new terminal
3. Open tmux

Images or other information
---------------------------

https://gist.github.com/709360eeb6e17949d7623208f36e1b04

**Comment by Eriner** [comment]
Nothing I've committed recently has changed any functionality related to that function. I think the problem is likely the fact that you've installed the `zim-git` package. Due to the `/usr/lib/zim` in the path, my guess the issue is permissions. I suggest you install zim locally (per-user) as documented in the README.md.

If that doesn't fix the issue, please let me know.

**Comment by Brottweiler** [comment]
Maybe should have mentioned that I use https://aur.archlinux.org/packages/zsh-zim-git/.

When uninstalling `zsh-zim-git` I get `find: ‘/usr/lib/zim’: No such file or directory`, and when I reinstall it I get `/usr/lib/zim/templates/zlogin:22: no matches found: /root/.zcomp^(*.zwc)(.)`.

Does that help?

**Comment by Eriner** [comment]
Yeah, it's because it has to do how initialization works against the current user. I suggest you install it on a user-by-user basis (or symlink). installing it to your home directory will fix this issue.

**Comment by Brottweiler** [comment]
Hmm, I'm wondering why so far it was working fine, but today I had this issue? Any idea why it just started happening?

**Comment by ishitatsuyuki** [comment]
Resolved: package has been updated.

**Comment by gavsiu** [comment]
@ishitatsuyuki Still getting this issue with the AUR package.

**Comment by Eriner** [comment]
Yes, unfortunately due to the way the packaging works, it prevents some optimizations and causes issues like this. I'm not going to work around this type of packaging. I suggest everyone with this package  remove the arch package and perform a normal git-based install.

**Comment by ishitatsuyuki** [comment]
I have updated the install script. (With a trick to sed out the disown)

`&!` disown the process and it's quite annoying for me. I would be happy to see it in a modular form, and make `zim_build_cache` a blocking function.

**Comment by Eriner** [comment]
> `&!` disown the process and it's quite annoying for me.

Can you clarify what you mean by this? What about it is annoying? As far as I can tell, that has nothing to do with the core issue here; it's about which user is executing these functions. If a non-root user executes the `.zlogin` file, they will be unable to write to `/usr/lib/`, as described by @Brottweiler in the OP:

> Opening tmux spams the terminal with a bunch of `zcompare:zcompile:2: can't write zwc file: /usr/lib/zim/modules/git/init.zsh.zwc messages`

This is a file-permissions issue; the `${ZDOTDIR}` is unwritable by a non-root user.

**Comment by ishitatsuyuki** [comment]
I'm prebuilding the cache during installation by emulating a login shell; disowning seems to trigger a race and cause the session to be killed. I have to manually pipe a modified zlogin then.

**Comment by Eriner** [comment]
This has nothing to do with a race; this has to do with `ZDOTDIR` being unwritable by the user. This cannot be solved without having an insecure set of permissions in `/usr/lib`. This isn't an issue that can be solved, which is why I recommend *removing* the package and leaving it up to the user to install. This isn't a solvable issue without introducing security problems.

**Comment by ishitatsuyuki** [comment]
Cache should be only generated once; how do you need to modify the compiles cache without modifying the original file, which is also read-only?

**Comment by Eriner** [comment]
No, you seem to fundamentally misunderstand. The cache will be rebuild whenever `.zlogin` is sourced, which is whenever the user logs into a TTY. This will target the files in `${ZDOTDIR}`, which for zsh-zim-git is unwritable because it is in `/usr/lib/`. **This needs to be how it works; cache should not be "only generated once"**. This ensures the files are byte-compiled whenever there are changes, and ensures that `.zshrc` and other files are bytecompiled. This is not a solvable problem without entering obstructionist levels of abstraction of the `.zlogin` function.

**Comment by Eriner** [comment]
The correct way to "install" zim in this case, imo, would be to provide some mechanism of copying the files to the users home directory in the same way that the zim installation is recommended in the README.md file at the root of the project. That would avoid this issue. Setting the `ZDOTDIR` to an unwritable directory is not the solution for a project like zim.

**Comment by ishitatsuyuki** [comment]
Why you even need to recompile if the source doesn't change? My package does the compilation on install (ofc as root) by emulating zlogin.

I'm assuming users doesn't modify the existing framework code anyway. zshrc, zimrc are kept customisable.

**Comment by Eriner** [comment]
> Why you even need to recompile if the source doesn't change?

What does this mean? It doesn't recompile if the "source" (I'm assuming you mean zim source) doesn't change--see the `zcompare` function. However, files such as `.zcompdump` and  `.zimrc` **will** change periodically. This is a programmatic way to `zcompile` them when necessary. The error message from the OP indicates that something is incorrect with your implementation of emulation, however I haven't personally investigated or invested time into the PKGBUILD, as I stand by my recommendation of not using a system-wide package; dotfiles are personal, and there is no need to introduce additional complexity.
